// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BankCardInfo struct {
	CardId         int64  `json:"cardId"`
	CustomerId     string `json:"customerId"`
	BankCardNumber string `json:"bankCardNumber"`
	BankName       string `json:"bankName"`
	CardBalance    string `json:"cardBalance"`
	IsVirtual      int    `json:"isVirtual"`
	BindStatus     string `json:"bindStatus"`
	BindTime       string `json:"bindTime"`
	UnbindTime     string `json:"unbindTime,omitempty"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type BehaviorStatisticsReq struct {
	CustomerId string `form:"customerId" validate:"required"`
	StartTime  string `form:"startTime,optional"`
	EndTime    string `form:"endTime,optional"`
}

type BehaviorStatisticsResp struct {
	TotalCount     int64               `json:"totalCount"`
	TypeStatistics []BehaviorTypeCount `json:"typeStatistics"`
}

type BehaviorTypeCount struct {
	BehaviorType string `json:"behaviorType"`
	Count        int64  `json:"count"`
}

type BindBankCardReq struct {
	CustomerId     string `json:"customerId" validate:"required"`
	BankCardNumber string `json:"bankCardNumber" validate:"required"`
	BankName       string `json:"bankName" validate:"required"`
	IsVirtual      int    `json:"isVirtual"`
	CardBalance    string `json:"cardBalance,omitempty"`
}

type BindBankCardResp struct {
	CardId int64 `json:"cardId"`
}

type CreateCustomerReq struct {
	CustomerName             string `json:"customerName" validate:"required"`
	CustomerType             string `json:"customerType" validate:"required"`
	IdType                   string `json:"idType" validate:"required"`
	IdNumber                 string `json:"idNumber" validate:"required"`
	RiskLevel                string `json:"riskLevel" validate:"required"`
	RiskEvaluationTime       string `json:"riskEvaluationTime" validate:"required"`
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime" validate:"required"`
	ContactPhone             string `json:"contactPhone,omitempty"`
	Email                    string `json:"email,omitempty"`
}

type CreateCustomerResp struct {
	CustomerId string `json:"customerId"`
}

type CustomerBehavior struct {
	BehaviorId       int64  `json:"behaviorId"`
	CustomerId       string `json:"customerId"`
	BehaviorType     string `json:"behaviorType"`
	BehaviorTime     string `json:"behaviorTime"`
	RelatedProductId string `json:"relatedProductId,omitempty"`
	BehaviorDetail   string `json:"behaviorDetail,omitempty"`
	IpAddress        string `json:"ipAddress,omitempty"`
	DeviceInfo       string `json:"deviceInfo,omitempty"`
	CreateTime       string `json:"createTime"`
}

type CustomerInfo struct {
	CustomerId               string `json:"customerId"`
	CustomerName             string `json:"customerName"`
	CustomerType             string `json:"customerType"`
	IdType                   string `json:"idType"`
	IdNumber                 string `json:"idNumber"`
	RiskLevel                string `json:"riskLevel"`
	RiskEvaluationTime       string `json:"riskEvaluationTime"`
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime"`
	ContactPhone             string `json:"contactPhone,omitempty"`
	Email                    string `json:"email,omitempty"`
	CreateTime               string `json:"createTime"`
	UpdateTime               string `json:"updateTime"`
}

type DeleteCustomerReq struct {
	CustomerId string `path:"customerId" validate:"required"`
}

type DeleteCustomerResp struct {
	Success bool `json:"success"`
}

type GetBankCardReq struct {
	CardId int64 `path:"cardId"`
}

type GetBankCardResp struct {
	BankCard BankCardInfo `json:"bankCard"`
}

type GetCustomerReq struct {
	CustomerId string `path:"customerId"`
}

type GetCustomerResp struct {
	Customer CustomerInfo `json:"customer"`
}

type ListBankCardReq struct {
	CustomerId string `form:"customerId" validate:"required"`
	BindStatus string `form:"bindStatus,optional"`
	IsVirtual  int    `form:"isVirtual,optional"`
}

type ListBankCardResp struct {
	Total int64          `json:"total"`
	List  []BankCardInfo `json:"list"`
}

type ListBehaviorReq struct {
	CustomerId       string `form:"customerId" validate:"required"`
	BehaviorType     string `form:"behaviorType,optional"`
	RelatedProductId string `form:"relatedProductId,optional"`
	StartTime        string `form:"startTime,optional"`
	EndTime          string `form:"endTime,optional"`
	Page             int    `form:"page,default=1"`
	PageSize         int    `form:"pageSize,default=20"`
}

type ListBehaviorResp struct {
	Total    int64              `json:"total"`
	List     []CustomerBehavior `json:"list"`
	Page     int                `json:"page"`
	PageSize int                `json:"pageSize"`
}

type ListCustomerReq struct {
	Page         int    `form:"page,default=1"`
	PageSize     int    `form:"pageSize,default=10"`
	CustomerName string `form:"customerName,optional"`
	CustomerType string `form:"customerType,optional"`
	RiskLevel    string `form:"riskLevel,optional"`
	IdNumber     string `form:"idNumber,optional"`
}

type ListCustomerResp struct {
	Total    int64          `json:"total"`
	List     []CustomerInfo `json:"list"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
}

type RecordBehaviorReq struct {
	CustomerId       string `json:"customerId" validate:"required"`
	BehaviorType     string `json:"behaviorType" validate:"required"`
	RelatedProductId string `json:"relatedProductId,omitempty"`
	BehaviorDetail   string `json:"behaviorDetail,omitempty"`
	IpAddress        string `json:"ipAddress,omitempty"`
	DeviceInfo       string `json:"deviceInfo,omitempty"`
}

type RecordBehaviorResp struct {
	BehaviorId int64 `json:"behaviorId"`
}

type Response struct {
	Code uint32      `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UnbindBankCardReq struct {
	CardId int64 `json:"cardId" validate:"required"`
}

type UnbindBankCardResp struct {
	Success bool `json:"success"`
}

type UpdateCardBalanceReq struct {
	CardId      int64  `json:"cardId" validate:"required"`
	Amount      string `json:"amount" validate:"required"`
	OperateType string `json:"operateType" validate:"required"`
	Remark      string `json:"remark,omitempty"`
}

type UpdateCardBalanceResp struct {
	NewBalance string `json:"newBalance"`
}

type UpdateCustomerReq struct {
	CustomerId               string `json:"customerId" validate:"required"`
	CustomerName             string `json:"customerName,omitempty"`
	RiskLevel                string `json:"riskLevel,omitempty"`
	RiskEvaluationTime       string `json:"riskEvaluationTime,omitempty"`
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime,omitempty"`
	ContactPhone             string `json:"contactPhone,omitempty"`
	Email                    string `json:"email,omitempty"`
}

type UpdateCustomerResp struct {
	Success bool `json:"success"`
}

type UpdateRiskEvaluationReq struct {
	CustomerId               string `json:"customerId" validate:"required"`
	RiskLevel                string `json:"riskLevel" validate:"required"`
	RiskEvaluationTime       string `json:"riskEvaluationTime" validate:"required"`
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime" validate:"required"`
}

type UpdateRiskEvaluationResp struct {
	Success bool `json:"success"`
}
