// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BankCardInfo struct {
	CardId         int64  `json:"cardId"`               // 银行卡ID
	CustomerId     string `json:"customerId"`           // 客户ID
	BankCardNumber string `json:"bankCardNumber"`       // 银行卡号(部分脱敏)
	BankName       string `json:"bankName"`             // 开户行名称
	CardBalance    string `json:"cardBalance"`          // 银行卡余额
	IsVirtual      int    `json:"isVirtual"`            // 是否虚拟银行卡: 1-是, 0-否
	BindStatus     string `json:"bindStatus"`           // 绑定状态
	BindTime       string `json:"bindTime"`             // 绑定时间
	UnbindTime     string `json:"unbindTime,omitempty"` // 解绑时间
	CreateTime     string `json:"createTime"`           // 创建时间
	UpdateTime     string `json:"updateTime"`           // 更新时间
}

type BehaviorStatisticsReq struct {
	CustomerId string `form:"customerId" validate:"required"` // 客户ID
	StartTime  string `form:"startTime,optional"`             // 开始时间
	EndTime    string `form:"endTime,optional"`               // 结束时间
}

type BehaviorStatisticsResp struct {
	TotalCount     int64               `json:"totalCount"`     // 总行为次数
	TypeStatistics []BehaviorTypeCount `json:"typeStatistics"` // 各类型统计
}

type BehaviorTypeCount struct {
	BehaviorType string `json:"behaviorType"` // 行为类型
	Count        int64  `json:"count"`        // 次数
}

type BindBankCardReq struct {
	CustomerId     string `json:"customerId" validate:"required"`     // 客户ID
	BankCardNumber string `json:"bankCardNumber" validate:"required"` // 银行卡号
	BankName       string `json:"bankName" validate:"required"`       // 开户行名称
	IsVirtual      int    `json:"isVirtual"`                          // 是否虚拟卡: 1-是, 0-否
	CardBalance    string `json:"cardBalance,omitempty"`              // 初始余额(虚拟卡需要)
}

type BindBankCardResp struct {
	CardId int64 `json:"cardId"` // 银行卡ID
}

type CreateCustomerReq struct {
	CustomerName             string `json:"customerName" validate:"required"`             // 客户姓名/企业名称
	CustomerType             string `json:"customerType" validate:"required"`             // 客户类型
	IdType                   string `json:"idType" validate:"required"`                   // 证件类型
	IdNumber                 string `json:"idNumber" validate:"required"`                 // 证件号码
	RiskLevel                string `json:"riskLevel" validate:"required"`                // 风险等级
	RiskEvaluationTime       string `json:"riskEvaluationTime" validate:"required"`       // 风险测评时间
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime" validate:"required"` // 风险测评过期时间
	ContactPhone             string `json:"contactPhone,omitempty"`                       // 联系电话
	Email                    string `json:"email,omitempty"`                              // 电子邮箱
}

type CreateCustomerResp struct {
	CustomerId string `json:"customerId"` // 客户ID
}

type CustomerBehavior struct {
	BehaviorId       int64  `json:"behaviorId"`                 // 行为ID
	CustomerId       string `json:"customerId"`                 // 客户ID
	BehaviorType     string `json:"behaviorType"`               // 行为类型
	BehaviorTime     string `json:"behaviorTime"`               // 行为时间
	RelatedProductId string `json:"relatedProductId,omitempty"` // 关联产品ID
	BehaviorDetail   string `json:"behaviorDetail,omitempty"`   // 行为详情(JSON)
	IpAddress        string `json:"ipAddress,omitempty"`        // IP地址
	DeviceInfo       string `json:"deviceInfo,omitempty"`       // 设备信息
	CreateTime       string `json:"createTime"`                 // 创建时间
}

type CustomerInfo struct {
	CustomerId               string `json:"customerId"`               // 客户唯一标识
	CustomerName             string `json:"customerName"`             // 客户姓名/企业名称
	CustomerType             string `json:"customerType"`             // 客户类型: 个人/企业
	IdType                   string `json:"idType"`                   // 证件类型
	IdNumber                 string `json:"idNumber"`                 // 证件号码(已加密)
	RiskLevel                string `json:"riskLevel"`                // 风险等级: R1-R5
	RiskEvaluationTime       string `json:"riskEvaluationTime"`       // 风险测评时间
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime"` // 风险测评过期时间
	ContactPhone             string `json:"contactPhone,omitempty"`   // 联系电话
	Email                    string `json:"email,omitempty"`          // 电子邮箱
	CreateTime               string `json:"createTime"`               // 创建时间
	UpdateTime               string `json:"updateTime"`               // 更新时间
}

type GetBankCardReq struct {
	CardId int64 `path:"cardId"` // 银行卡ID
}

type GetBankCardResp struct {
	BankCard BankCardInfo `json:"bankCard"` // 银行卡信息
}

type GetCustomerReq struct {
	CustomerId string `path:"customerId"` // 客户ID
}

type GetCustomerResp struct {
	Customer CustomerInfo `json:"customer"` // 客户信息
}

type ListBankCardReq struct {
	CustomerId string `form:"customerId" validate:"required"` // 客户ID
	BindStatus string `form:"bindStatus,optional"`            // 绑定状态
	IsVirtual  int    `form:"isVirtual,optional"`             // 是否虚拟卡: -1-全部, 0-真实卡, 1-虚拟卡
}

type ListBankCardResp struct {
	Total int64          `json:"total"` // 总数
	List  []BankCardInfo `json:"list"`  // 银行卡列表
}

type ListBehaviorReq struct {
	CustomerId       string `form:"customerId" validate:"required"` // 客户ID
	BehaviorType     string `form:"behaviorType,optional"`          // 行为类型
	RelatedProductId string `form:"relatedProductId,optional"`      // 关联产品ID
	StartTime        string `form:"startTime,optional"`             // 开始时间
	EndTime          string `form:"endTime,optional"`               // 结束时间
	Page             int    `form:"page,default=1"`                 // 页码
	PageSize         int    `form:"pageSize,default=20"`            // 每页数量
}

type ListBehaviorResp struct {
	Total    int64              `json:"total"`    // 总数
	List     []CustomerBehavior `json:"list"`     // 行为列表
	Page     int                `json:"page"`     // 当前页
	PageSize int                `json:"pageSize"` // 每页数量
}

type ListCustomerReq struct {
	Page         int    `form:"page,default=1"`        // 页码
	PageSize     int    `form:"pageSize,default=10"`   // 每页数量
	CustomerName string `form:"customerName,optional"` // 客户名称(模糊查询)
	CustomerType string `form:"customerType,optional"` // 客户类型
	RiskLevel    string `form:"riskLevel,optional"`    // 风险等级
	IdNumber     string `form:"idNumber,optional"`     // 证件号码(精确查询)
}

type ListCustomerResp struct {
	Total    int64          `json:"total"`    // 总数
	List     []CustomerInfo `json:"list"`     // 客户列表
	Page     int            `json:"page"`     // 当前页
	PageSize int            `json:"pageSize"` // 每页数量
}

type RecordBehaviorReq struct {
	CustomerId       string `json:"customerId" validate:"required"`   // 客户ID
	BehaviorType     string `json:"behaviorType" validate:"required"` // 行为类型
	RelatedProductId string `json:"relatedProductId,omitempty"`       // 关联产品ID
	BehaviorDetail   string `json:"behaviorDetail,omitempty"`         // 行为详情(JSON字符串)
	IpAddress        string `json:"ipAddress,omitempty"`              // IP地址
	DeviceInfo       string `json:"deviceInfo,omitempty"`             // 设备信息
}

type RecordBehaviorResp struct {
	BehaviorId int64 `json:"behaviorId"` // 行为ID
}

type Response struct {
	Code uint32      `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UnbindBankCardReq struct {
	CardId int64 `json:"cardId" validate:"required"` // 银行卡ID
}

type UnbindBankCardResp struct {
	Success bool `json:"success"` // 是否成功
}

type UpdateCardBalanceReq struct {
	CardId      int64  `json:"cardId" validate:"required"`      // 银行卡ID
	Amount      string `json:"amount" validate:"required"`      // 变动金额(正数为增加,负数为减少)
	OperateType string `json:"operateType" validate:"required"` // 操作类型: recharge-充值, consume-消费
	Remark      string `json:"remark,omitempty"`                // 备注
}

type UpdateCardBalanceResp struct {
	NewBalance string `json:"newBalance"` // 更新后余额
}

type UpdateCustomerReq struct {
	CustomerId               string `json:"customerId" validate:"required"`     // 客户ID
	CustomerName             string `json:"customerName,omitempty"`             // 客户姓名/企业名称
	RiskLevel                string `json:"riskLevel,omitempty"`                // 风险等级
	RiskEvaluationTime       string `json:"riskEvaluationTime,omitempty"`       // 风险测评时间
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime,omitempty"` // 风险测评过期时间
	ContactPhone             string `json:"contactPhone,omitempty"`             // 联系电话
	Email                    string `json:"email,omitempty"`                    // 电子邮箱
}

type UpdateCustomerResp struct {
	Success bool `json:"success"` // 是否成功
}

type UpdateRiskEvaluationReq struct {
	CustomerId               string `json:"customerId" validate:"required"`               // 客户ID
	RiskLevel                string `json:"riskLevel" validate:"required"`                // 风险等级
	RiskEvaluationTime       string `json:"riskEvaluationTime" validate:"required"`       // 风险测评时间
	RiskEvaluationExpireTime string `json:"riskEvaluationExpireTime" validate:"required"` // 风险测评过期时间
}

type UpdateRiskEvaluationResp struct {
	Success bool `json:"success"` // 是否成功
}
