// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerInfoFieldNames          = builder.RawFieldNames(&CustomerInfo{})
	customerInfoRows                = strings.Join(customerInfoFieldNames, ",")
	customerInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(customerInfoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(customerInfoFieldNames, "`customer_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerInfoModel interface {
		Insert(ctx context.Context, data *CustomerInfo) (sql.Result, error)
		FindOne(ctx context.Context, customerId string) (*CustomerInfo, error)
		Update(ctx context.Context, data *CustomerInfo) error
		Delete(ctx context.Context, customerId string) error
	}

	defaultCustomerInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerInfo struct {
		CustomerId               string         `db:"customer_id"`                 // 客户唯一标识，客户编号
		CustomerName             string         `db:"customer_name"`               // 客户姓名（个人）/企业名称（企业）
		CustomerType             string         `db:"customer_type"`               // 客户类型，如“个人”“企业”
		IdType                   string         `db:"id_type"`                     // 证件类型，如“身份证”“营业执照”
		IdNumber                 string         `db:"id_number"`                   // 证件号码，加密存储
		RiskLevel                string         `db:"risk_level"`                  // 客户风险等级，如“R1”“R2”“R3”“R4”“R5”
		RiskEvaluationTime       time.Time      `db:"risk_evaluation_time"`        // 风险测评时间
		RiskEvaluationExpireTime time.Time      `db:"risk_evaluation_expire_time"` // 风险测评过期时间
		ContactPhone             sql.NullString `db:"contact_phone"`               // 联系电话，加密存储
		Email                    sql.NullString `db:"email"`                       // 电子邮箱
		CreateTime               time.Time      `db:"create_time"`                 // 客户创建时间（开户时间）
		UpdateTime               time.Time      `db:"update_time"`                 // 客户信息更新时间
		DeletedAt                sql.NullTime   `db:"deleted_at"`
	}
)

func newCustomerInfoModel(conn sqlx.SqlConn) *defaultCustomerInfoModel {
	return &defaultCustomerInfoModel{
		conn:  conn,
		table: "`customer_info`",
	}
}

func (m *defaultCustomerInfoModel) Delete(ctx context.Context, customerId string) error {
	query := fmt.Sprintf("delete from %s where `customer_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, customerId)
	return err
}

func (m *defaultCustomerInfoModel) FindOne(ctx context.Context, customerId string) (*CustomerInfo, error) {
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? limit 1", customerInfoRows, m.table)
	var resp CustomerInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, customerId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerInfoModel) Insert(ctx context.Context, data *CustomerInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, customerInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.CustomerName, data.CustomerType, data.IdType, data.IdNumber, data.RiskLevel, data.RiskEvaluationTime, data.RiskEvaluationExpireTime, data.ContactPhone, data.Email, data.DeletedAt)
	return ret, err
}

func (m *defaultCustomerInfoModel) Update(ctx context.Context, data *CustomerInfo) error {
	query := fmt.Sprintf("update %s set %s where `customer_id` = ?", m.table, customerInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CustomerName, data.CustomerType, data.IdType, data.IdNumber, data.RiskLevel, data.RiskEvaluationTime, data.RiskEvaluationExpireTime, data.ContactPhone, data.Email, data.DeletedAt, data.CustomerId)
	return err
}

func (m *defaultCustomerInfoModel) tableName() string {
	return m.table
}
