// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerBehaviorFieldNames          = builder.RawFieldNames(&CustomerBehavior{})
	customerBehaviorRows                = strings.Join(customerBehaviorFieldNames, ",")
	customerBehaviorRowsExpectAutoSet   = strings.Join(stringx.Remove(customerBehaviorFieldNames, "`behavior_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerBehaviorRowsWithPlaceHolder = strings.Join(stringx.Remove(customerBehaviorFieldNames, "`behavior_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerBehaviorModel interface {
		Insert(ctx context.Context, data *CustomerBehavior) (sql.Result, error)
		FindOne(ctx context.Context, behaviorId int64) (*CustomerBehavior, error)
		Update(ctx context.Context, data *CustomerBehavior) error
		Delete(ctx context.Context, behaviorId int64) error
	}

	defaultCustomerBehaviorModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerBehavior struct {
		BehaviorId       int64          `db:"behavior_id"`        // 行为记录唯一标识，自增
		CustomerId       string         `db:"customer_id"`        // 客户标识，关联客户信息表
		BehaviorType     string         `db:"behavior_type"`      // 行为类型，如“产品查询”“申购”“赎回”“风险测评”
		BehaviorTime     time.Time      `db:"behavior_time"`      // 行为发生时间
		RelatedProductId sql.NullString `db:"related_product_id"` // 关联产品ID，如查询、申购、赎回的产品
		BehaviorDetail   sql.NullString `db:"behavior_detail"`    // 行为详情，如查询的时间范围、申购的金额
		IpAddress        sql.NullString `db:"ip_address"`         // 行为发生时的IP地址
		DeviceInfo       sql.NullString `db:"device_info"`        // 设备信息，如“PC端-Windows-Chrome”“移动端-Android-微信小程序”
		CreateTime       time.Time      `db:"create_time"`        // 记录创建时间
	}
)

func newCustomerBehaviorModel(conn sqlx.SqlConn) *defaultCustomerBehaviorModel {
	return &defaultCustomerBehaviorModel{
		conn:  conn,
		table: "`customer_behavior`",
	}
}

func (m *defaultCustomerBehaviorModel) Delete(ctx context.Context, behaviorId int64) error {
	query := fmt.Sprintf("delete from %s where `behavior_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, behaviorId)
	return err
}

func (m *defaultCustomerBehaviorModel) FindOne(ctx context.Context, behaviorId int64) (*CustomerBehavior, error) {
	query := fmt.Sprintf("select %s from %s where `behavior_id` = ? limit 1", customerBehaviorRows, m.table)
	var resp CustomerBehavior
	err := m.conn.QueryRowCtx(ctx, &resp, query, behaviorId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerBehaviorModel) Insert(ctx context.Context, data *CustomerBehavior) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, customerBehaviorRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.BehaviorType, data.BehaviorTime, data.RelatedProductId, data.BehaviorDetail, data.IpAddress, data.DeviceInfo)
	return ret, err
}

func (m *defaultCustomerBehaviorModel) Update(ctx context.Context, data *CustomerBehavior) error {
	query := fmt.Sprintf("update %s set %s where `behavior_id` = ?", m.table, customerBehaviorRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.BehaviorType, data.BehaviorTime, data.RelatedProductId, data.BehaviorDetail, data.IpAddress, data.DeviceInfo, data.BehaviorId)
	return err
}

func (m *defaultCustomerBehaviorModel) tableName() string {
	return m.table
}
