// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerBankCardFieldNames          = builder.RawFieldNames(&CustomerBankCard{})
	customerBankCardRows                = strings.Join(customerBankCardFieldNames, ",")
	customerBankCardRowsExpectAutoSet   = strings.Join(stringx.Remove(customerBankCardFieldNames, "`card_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerBankCardRowsWithPlaceHolder = strings.Join(stringx.Remove(customerBankCardFieldNames, "`card_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerBankCardModel interface {
		Insert(ctx context.Context, data *CustomerBankCard) (sql.Result, error)
		FindOne(ctx context.Context, cardId int64) (*CustomerBankCard, error)
		FindOneByCustomerIdBankCardNumber(ctx context.Context, customerId string, bankCardNumber string) (*CustomerBankCard, error)
		Update(ctx context.Context, data *CustomerBankCard) error
		Delete(ctx context.Context, cardId int64) error
	}

	defaultCustomerBankCardModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerBankCard struct {
		CardId         int64        `db:"card_id"`          // 银行卡记录唯一标识，自增
		CustomerId     string       `db:"customer_id"`      // 客户标识，关联客户信息表
		BankCardNumber string       `db:"bank_card_number"` // 银行卡号，加密存储
		BankName       string       `db:"bank_name"`        // 开户行名称，如“中国工商银行”“中信银行”
		CardBalance    float64      `db:"card_balance"`     // 银行卡余额，虚拟充值金额需标注
		IsVirtual      int64        `db:"is_virtual"`       // 是否虚拟银行卡，1-是，0-否
		BindStatus     string       `db:"bind_status"`      // 绑定状态，如“正常”“已解绑”
		BindTime       time.Time    `db:"bind_time"`        // 绑定时间
		UnbindTime     sql.NullTime `db:"unbind_time"`      // 解绑时间，解绑时记录
		CreateTime     time.Time    `db:"create_time"`      // 记录创建时间
		UpdateTime     time.Time    `db:"update_time"`      // 记录更新时间
		DeletedAt      sql.NullTime `db:"deleted_at"`
	}
)

func newCustomerBankCardModel(conn sqlx.SqlConn) *defaultCustomerBankCardModel {
	return &defaultCustomerBankCardModel{
		conn:  conn,
		table: "`customer_bank_card`",
	}
}

func (m *defaultCustomerBankCardModel) Delete(ctx context.Context, cardId int64) error {
	query := fmt.Sprintf("delete from %s where `card_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, cardId)
	return err
}

func (m *defaultCustomerBankCardModel) FindOne(ctx context.Context, cardId int64) (*CustomerBankCard, error) {
	query := fmt.Sprintf("select %s from %s where `card_id` = ? limit 1 and `deleted_at` is null", customerBankCardRows, m.table)
	var resp CustomerBankCard
	err := m.conn.QueryRowCtx(ctx, &resp, query, cardId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerBankCardModel) FindOneByCustomerIdBankCardNumber(ctx context.Context, customerId string, bankCardNumber string) (*CustomerBankCard, error) {
	var resp CustomerBankCard
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? and `bank_card_number` = ? limit 1", customerBankCardRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, customerId, bankCardNumber)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerBankCardModel) Insert(ctx context.Context, data *CustomerBankCard) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, customerBankCardRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.BankCardNumber, data.BankName, data.CardBalance, data.IsVirtual, data.BindStatus, data.BindTime, data.UnbindTime, data.DeletedAt)
	return ret, err
}

func (m *defaultCustomerBankCardModel) Update(ctx context.Context, newData *CustomerBankCard) error {
	query := fmt.Sprintf("update %s set %s where `card_id` = ?", m.table, customerBankCardRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CustomerId, newData.BankCardNumber, newData.BankName, newData.CardBalance, newData.IsVirtual, newData.BindStatus, newData.BindTime, newData.UnbindTime, newData.DeletedAt, newData.CardId)
	return err
}

func (m *defaultCustomerBankCardModel) tableName() string {
	return m.table
}
