// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	bankcard "github.com/Nozomi9967/wmss-customer-api/internal/handler/bankcard"
	behavior "github.com/Nozomi9967/wmss-customer-api/internal/handler/behavior"
	customer "github.com/Nozomi9967/wmss-customer-api/internal/handler/customer"
	"github.com/Nozomi9967/wmss-customer-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 更新银行卡余额
					Method:  http.MethodPut,
					Path:    "/balance",
					Handler: bankcard.UpdateCardBalanceHandler(serverCtx),
				},
				{
					// 绑定银行卡
					Method:  http.MethodPost,
					Path:    "/bind",
					Handler: bankcard.BindBankCardHandler(serverCtx),
				},
				{
					// 查询银行卡详情
					Method:  http.MethodGet,
					Path:    "/info/:cardId",
					Handler: bankcard.GetBankCardHandler(serverCtx),
				},
				{
					// 查询客户银行卡列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: bankcard.ListBankCardHandler(serverCtx),
				},
				{
					// 解绑银行卡
					Method:  http.MethodPost,
					Path:    "/unbind",
					Handler: bankcard.UnbindBankCardHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/bank-card"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 查询客户行为列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: behavior.ListBehaviorHandler(serverCtx),
				},
				{
					// 记录客户行为
					Method:  http.MethodPost,
					Path:    "/record",
					Handler: behavior.RecordBehaviorHandler(serverCtx),
				},
				{
					// 客户行为统计
					Method:  http.MethodGet,
					Path:    "/statistics",
					Handler: behavior.BehaviorStatisticsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/behavior"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					// 创建客户
					Method:  http.MethodPost,
					Path:    "/info",
					Handler: customer.CreateCustomerHandler(serverCtx),
				},
				{
					// 更新客户信息
					Method:  http.MethodPut,
					Path:    "/info",
					Handler: customer.UpdateCustomerHandler(serverCtx),
				},
				{
					// 查询客户详情
					Method:  http.MethodGet,
					Path:    "/info/:customerId",
					Handler: customer.GetCustomerHandler(serverCtx),
				},
				{
					// 逻辑删除客户信息
					Method:  http.MethodDelete,
					Path:    "/info/:customerId",
					Handler: customer.DeleteCustomerHandler(serverCtx),
				},
				{
					// 查询客户列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: customer.ListCustomerHandler(serverCtx),
				},
				{
					// 更新风险测评
					Method:  http.MethodPut,
					Path:    "/risk-evaluation",
					Handler: customer.UpdateRiskEvaluationHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/customer"),
	)
}
